### ISSUE TITLE
1.3.3: ErrorException: Notice: Undefined index: format

### ISSUE THREAD

**Issue by lkraav** [OllieJones/index-wp-mysql-for-speeed#1] opened 2021-11-29 12:50 UTC
Fresh installation, no action has been taken yet, just displaying information.

Traceback https://sentry.io/share/issue/c7eb9b3ad76740c48c96ba79b95ae3ca/

Example cmdline

```
[~/www]# wp index-mysql tables
Index WP MySQL For Speed 1.3.3
Versions MySQL:10.3.27-MariaDB-log WordPress:5.8.2 php:7.4.18
Notice: Undefined index: format in /home/www/public_html/wp-content/plugins/index-wp-mysql-for-speed/code/cli.php on line 326
+----------+--------+---------+-------------+--------------+----------------+--------+------------+--------------------+
| table    | prefix | count   | distinct_id | distinct_key | autoload_count | engine | row_format | collation          |
+----------+--------+---------+-------------+--------------+----------------+--------+------------+--------------------+
| comments | wp_    | 856252  | 65865       |              |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
| options  | wp_    | 3706    |             |              | 2450           | InnoDB | Compact    | utf8mb4_unicode_ci |
| postmeta | wp_    | 4942770 |             | 17343        |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
| posts    | wp_    | 4250664 |             |              |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
| termmeta | wp_    | 1978    |             | 22           |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
| usermeta | wp_    | 1944811 | 54022       | 22354        |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
| users    | wp_    | 25171   |             |              |                | InnoDB | Dynamic    | utf8mb4_unicode_ci |
+----------+--------+---------+-------------+--------------+----------------+--------+------------+--------------------+
Notice: Undefined index: format in /home/www/public_html/wp-content/plugins/index-wp-mysql-for-speed/code/cli.php on line 345
+-------------+---------------------------+------------------------------------------------------------------------+
| table       | key                       | definition                                                             |
+-------------+---------------------------+------------------------------------------------------------------------+
| wp_postmeta | PRIMARY KEY               | ADD PRIMARY KEY (meta_id)                                              |
| wp_postmeta | meta_key                  | ADD KEY meta_key (meta_key(191))                                       |
| wp_postmeta | post_id                   | ADD KEY post_id (post_id)                                              |
| wp_postmeta | post_id_2                 | ADD KEY post_id_2 (post_id, meta_key)                                  |
| wp_usermeta | PRIMARY KEY               | ADD PRIMARY KEY (umeta_id)                                             |
| wp_usermeta | meta_key                  | ADD KEY meta_key (meta_key(191))                                       |
| wp_usermeta | user_id                   | ADD KEY user_id (user_id)                                              |
| wp_termmeta | PRIMARY KEY               | ADD PRIMARY KEY (meta_id)                                              |
| wp_termmeta | meta_key                  | ADD KEY meta_key (meta_key(191))                                       |
| wp_termmeta | term_id                   | ADD KEY term_id (term_id)                                              |
| wp_options  | PRIMARY KEY               | ADD PRIMARY KEY (option_id)                                            |
| wp_options  | option_name               | ADD UNIQUE KEY option_name (option_name)                               |
| wp_options  | autoload                  | ADD KEY autoload (autoload)                                            |
| wp_posts    | PRIMARY KEY               | ADD PRIMARY KEY (ID)                                                   |
| wp_posts    | bsearch_content           | ADD KEY bsearch_content (post_content)                                 |
| wp_posts    | bsearch_title             | ADD KEY bsearch_title (post_title)                                     |
| wp_posts    | post_author               | ADD KEY post_author (post_author)                                      |
| wp_posts    | post_name                 | ADD KEY post_name (post_name(191))                                     |
| wp_posts    | post_parent               | ADD KEY post_parent (post_parent)                                      |
| wp_posts    | type_status_date          | ADD KEY type_status_date (post_type, post_status, post_date, ID)       |
| wp_comments | PRIMARY KEY               | ADD PRIMARY KEY (comment_ID)                                           |
| wp_comments | comment_approved_date_gmt | ADD KEY comment_approved_date_gmt (comment_approved, comment_date_gmt) |
| wp_comments | comment_author_email      | ADD KEY comment_author_email (comment_author_email(10))                |
| wp_comments | comment_date_gmt          | ADD KEY comment_date_gmt (comment_date_gmt)                            |
| wp_comments | comment_parent            | ADD KEY comment_parent (comment_parent)                                |
| wp_comments | comment_post_ID           | ADD KEY comment_post_ID (comment_post_ID)                              |
| wp_comments | comment_type              | ADD KEY comment_type (comment_type)                                    |
| wp_comments | comment_type_user_id      | ADD KEY comment_type_user_id (comment_type, user_id)                   |
| wp_comments | woo_idx_comment_type      | ADD KEY woo_idx_comment_type (comment_type)                            |
+-------------+---------------------------+------------------------------------------------------------------------+
```

**Comment by OllieJones** [comment] 2021-12-11 21:49
Duplicate of #6 
Thanks for the bug report. Fix coming soon!

**Closed as completed by OllieJones** 2021-12-11 21:49 UTC
